# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

# export GITHUB_TOKEN="4c9b8d370bcc90db2f97298df5cac45f187ee0fa"
before:
  hooks:
    # You may remove this if you don't use go modules.
#    - go mod download
# you may remove this if you don't need go generate
#    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    id: "gopaste"
    binary: "gopaste"
    goos:
      - darwin
      - freebsd
      - linux
      - netbsd
      - openbsd
      - windows
archives:
  -
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
        darwin: Darwin
        linux: Linux
        windows: Windows
        386: i386
        amd64: x86_64
    format_overrides:
        - goos: windows
          format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "v{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
